E2E test menu
digi-serve/kitchensink_app pull request #14
Opened 2022-03-07 07:39 UTC by guyyoo

2022-03-07 07:57 UTC, nh758 requested changes
Good start. A few things to fix.

2022-03-07 07:57 UTC, nh758 commented on kitchenSink.json
> +                        "menuTextRight": "Text3"
I like this change!

2022-03-07 07:57 UTC, nh758 commented on test_cases/Menu.js
> +          .click();
You do this in each test. Please move into a BeforeEach hook

2022-03-07 07:57 UTC, nh758 commented on test_cases/Menu.js
> +          .should("include.text", "7")
I think you can simplify this to `.should('exist')`. We don't want to test the Chart Widget here.

2022-03-07 07:57 UTC, nh758 commented on test_cases/Menu.js
> +        )
I don't think you need to get the element again. Can move the `click()` to line 90

2022-03-07 07:57 UTC, nh758 commented on test_cases/Menu.js
> +          .should("include.text", "Home")
missing `;` and some other places. Maybe run eslint/prettier?

2022-03-07 09:43 UTC, nh758 approved these changes
Looks good.

2022-03-07 10:06 UTC, cmboyman commented
pretty good

2022-03-08 03:53 UTC, cmboyman approved these changes
very good.

2022-03-08 07:27 UTC, merged